// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/projeto-korp": {
            "get": {
                "description": "Returns the project name and the current time in UTC (RFC 3339), resolved on every request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projeto-korp"
                ],
                "summary": "Project name and current UTC time",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ProjetoKorpResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Correlation id, echoed from the request or generated"
                            }
                        }
                    },
                    "405": {
                        "description": "Method not allowed (Allow: GET, HEAD)",
                        "schema": {
                            "$ref": "#/definitions/problem.Problem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ProjetoKorpResponse": {
            "type": "object",
            "properties": {
                "horario": {
                    "type": "string",
                    "example": "2026-09-07T12:00:00Z"
                },
                "nome": {
                    "type": "string",
                    "example": "Projeto Korp"
                }
            }
        },
        "problem.Problem": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "no route for GET /x"
                },
                "instance": {
                    "type": "string",
                    "example": "/x"
                },
                "request_id": {
                    "type": "string",
                    "example": "7f2c1a1e-3b0e-4d8f-9a44-1d2f0c3b6a90"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                },
                "title": {
                    "type": "string",
                    "example": "Not Found"
                },
                "type": {
                    "type": "string",
                    "example": "about:blank"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "http-server-projeto-korp",
	Description:      "Serviço HTTP do Desafio DevOps \"Projeto Korp\": GET /projeto-korp devolve o nome do projeto e o horário atual em UTC, resolvido a cada requisição.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
